#!/bin/sh
### BEGIN INIT INFO
# Provides:          pi_gen_extended_once_config
# Required-Start:
# Required-Stop:
# Default-Start: 3
# Default-Stop:
# Short-Description: Configure from /boot/pi_gen_extended_device_config.sh
# Description:
### END INIT INFO
. /lib/lsb/init-functions
case "$1" in
  start)
    log_daemon_msg "Starting pi_gen_extended_once_config"
    ROOT_DEV=$(findmnt / -o source -n) &&
    /boot/pi_gen_extended_device_config.sh &&
    update-rc.d pi_gen_extended_once_config remove &&
    rm /etc/init.d/pi_gen_extended_once_config &&
    log_end_msg $?
    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac
